<H2>Netflix Movie Recommendor</H2>
<h3>Importing Libraries</h3>

In [155]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

In [156]:
df = pd.read_csv(r"D:\documents\codeit\Netflix movie recommender\netflix movie recommender\tmdb_5000_movie.csv")
df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

<h3>Check Data</h3>

In [157]:
df.shape

(4803, 20)

In [158]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [159]:
df.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [160]:
df = df[['genres','id','title','overview','tagline','keywords']]

In [161]:
df['tagline'] = df['tagline'].fillna('')
df['overview'] = df['overview'].fillna('')

In [162]:
df.isnull().sum()

genres      0
id          0
title       0
overview    0
tagline     0
keywords    0
dtype: int64

In [163]:
df = df.copy()

<h3>List Function</h3>

In [164]:
#function to convert dictionary to list
import ast
def convertfun(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [165]:
df['genres'] = df['genres'].apply(convertfun)

In [166]:
df.head(2)

,genres,id,title,overview,tagline,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,"[Adventure, Fantasy, Action]",285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."

In [167]:
df['keywords']=df['keywords'].apply(convertfun)

In [168]:

df.head(2)

,genres,id,title,overview,tagline,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","[ocean, drug abuse, exotic island, east india ..."

In [169]:
df2['overview'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

<h3>Split each items from overview and tagline to list</h3>

In [170]:
df['overview'] = df['overview'].apply(lambda x: x.split())
df['tagline'] = df['tagline'].apply(lambda x: x.split())

In [171]:
df['overview'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [173]:
df['tagline'][0]

['Enter', 'the', 'World', 'of', 'Pandora.']

<h3>Removing Spaces and making one word</h3>

In [174]:
df['genres'] = df['genres'].apply(lambda x: [i.replace(" ","") for i in x])
df['keywords'] = df['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
df['overview'] = df['overview'].apply(lambda x: [i.replace(" ","") for i in x])
df['tagline'] = df['tagline'].apply(lambda x: [i.replace(" ","") for i in x])

In [175]:
df.head(2)

,genres,id,title,overview,tagline,keywords
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Enter, the, World, of, Pandora.]","[cultureclash, future, spacewar, spacecolony, ..."
1,"[Adventure, Fantasy, Action]",285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[At, the, end, of, the, world,, the, adventure...","[ocean, drugabuse, exoticisland, eastindiatrad..."

<h3>Merging all items to form tag</h3>

In [176]:
df['tag'] = df['genres'] + df['overview'] + df['tagline'] + df['keywords']

In [177]:
df.head(2)

,genres,id,title,overview,tagline,keywords,tag
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Enter, the, World, of, Pandora.]","[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction, I..."
1,"[Adventure, Fantasy, Action]",285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[At, the, end, of, the, world,, the, adventure...","[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action, Captain, Barbossa..."

<h3>Making new data</h3>

In [178]:
movie = df[['id','title','tag']]

In [179]:
movie = movie.copy()

In [180]:
movie.head(2)

,id,title,tag
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, I..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, Captain, Barbossa..."

In [181]:
# convert list in tags to string
movie['tag'] = movie['tag'].apply(lambda x:" ".join(x))

In [182]:
movie.head(2)

,id,title,tag
0,19995,Avatar,Action Adventure Fantasy ScienceFiction In the...
1,285,Pirates of the Caribbean: At World's End,"Adventure Fantasy Action Captain Barbossa, lon..."

In [183]:
# convert to lower
movie['tag'] =  movie['tag'].apply(lambda x: x.lower())

In [184]:
movie['tag'][0]

'action adventure fantasy sciencefiction in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. enter the world of pandora. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d'

<h3>Vectorization</h3>

<h3>Stem Function</h3>

In [185]:
# stem before vectorizationothere wise wrong
import nltk 
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [186]:
def stem(text):
    x=[]
    for i in text.split():
        x.append(ps.stem(i))
    return " ".join(x)

In [97]:
movie['tag'] = movie['tag'].apply(stem)

In [187]:
movie['tag'][0]

'action adventure fantasy sciencefiction in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. enter the world of pandora. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d'

In [188]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,stop_words = 'english')

In [189]:
vector = cv.fit_transform(movie['tag']).toarray()

In [190]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4803, 5000))

In [191]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'],
      shape=(5000,), dtype=object)

<h3>Finding Distance between movie</h3>

In [192]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)

In [193]:
similarity[1]

array([0.13558154, 1.        , 0.09240617, ..., 0.05003128, 0.02475369,
       0.        ], shape=(4803,))

In [194]:
similarity.shape

(4803, 4803)

In [195]:
sorted(list(enumerate(similarity[0])),reverse=True, key=lambda x:x[1])[1:6]

[(539, np.float64(0.25993762245501817)),
 (582, np.float64(0.24119095530943302)),
 (1191, np.float64(0.23596995186213465)),
 (322, np.float64(0.23084512921915967)),
 (1326, np.float64(0.23078316568852544))]

In [196]:
def recommend(movie_name):
    index = movie[movie['title']==movie_name].index[0]
    distances = similarity[index]
    flim_list = sorted(list(enumerate(distances)),reverse = True, key = lambda x: x[1])[1:6]
    
    for i in flim_list:
        print(movie.iloc[i[0]].title)

In [200]:
recommend('The Matrix Reloaded')

The Matrix Revolutions
The Matrix
Dark City
Commando
Akira

In [201]:
import pickle

In [202]:
pickle.dump(movie,open('movie.pkl','wb'))

In [203]:
pickle.dump(similarity,open('similarity.pkl','wb'))